### ISSUE TITLE
Multi-GPU장시간 사용시 GPU 온도 문제로 비정상 동작

### ISSUE THREAD

**Issue by jhgoh** [sic-khu/sichpc#16]
Multi-GPU job을 장시간 사용시 비정상 동작 하는 것으로 보임.

```
Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. [E ProcessGroupNCCL.cpp:495] To avoid data inconsistency, we are taking the entire process down.

[Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=27630, OpType=ALLREDUCE, NumelIn=43521, NumelOut=43521, Timeout(ms)=1800000) ran for 1800859 milliseconds before timing out. terminate called after throwing an instance of 'std::runtime_error'

torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGABRT
```

<img width="1416" alt="image" src="https://github.com/sic-khu/sichpc/assets/4388926/61c2854c-5e75-4ab5-87f0-93f1cedc5b99">

**Comment by jhgoh** [comment]
업체 연락해 조치함. @ChangHyunYoo92 @hydro-carbo-nitro 팬 설정 조정 후 온도 낮아짐.

**Comment by hydro-carbo-nitro** [comment]
쿨러 효율을 높이면 소음이 너무 커져 복도는 물론 교수회의실, 물리학과 세미나실에서 조용히 있을 경우 쿨러 돌아가는 소리가 들림. 소음 최소화를 위해 GPU 온도가 60도씨를 유지할 수 있는 offset 체크중.

**Comment by hydro-carbo-nitro** [comment]
업체 확인 결과 애초에 쿨링팬이 꺼져있었다고 합니다... offset low 상태로도 온도 유지가 잘 되어서 low로 진행 하겠습니다.

**Comment by jhgoh** [comment]
관련 정보는 여기에 있음: 
https://www.dell.com/support/kbdoc/en-us/000138639/adjusting-fan-speed-offset-in-dell-poweredge-12th-generation-servers

terminal상에서도 조절 가능함 (단, racadm 명령어가 설치되어 있어야 함. sichpc메인 서버에는 설치되어 있으나, disless노드들에서는 설치되지 않은 것 같음.)

세팅값 확인:
```
racadm get system.thermalsettings.FanSpeedOffset
```

세팅값 변경:
```
racadm set system.thermalsettings.FanSpeedOffset low
```

iDRAC 버전에 따라서 low 대신 숫자 (0=low)로 바꿔 넣어주어야 할 수도 있음.
