### ISSUE TITLE
학부생 실습 계정 permission 관련

### ISSUE THREAD

**Issue by hydro-carbo-nitro** [sic-khu/sichpc#5]

**Comment by hydro-carbo-nitro** [comment]
1. 기존에 존재하는 학생들 계정(s20* 계정들)을 아직은 지우지 않고 비밀번호만 적당한 비밀번호로 바꿔놓으려 합니다.

그러던 중 s2022100703 계정이 최근에 클러스터를 사용중인걸 확인했습니다. 원칙대로면 방학중에는 허가를 받은 인원만 사용하는게 맞으나, chyoo(유창현 선배) 이외에는 사용중인 인원이 없으며, history로 확인해보니 slurm을 통한 스케쥴링도 착실히 하고있는 것 같아 시스템에는 큰 영향을 줄 것 같지 않아 일단 건들지 않았습니다.

이 학생이 클러스터를 계속 사용하게 할까요 아니면 이야기를 해서 별도 조치를 취할까요?

**Comment by jhgoh** [comment]
이 이슈는 해당 유저에게 정식 계정을 만들어 사용할 수 있게 하면서 해결된 것으로 보이는 데 맞죠? 맞으면 close하면 될 것 같아요.
