### ISSUE TITLE
MATLAB 관련

### ISSUE THREAD

**Issue by hydro-carbo-nitro** [sic-khu/sichpc#6]
MATLAB 설치 후 작동 확인 완료. 추후 필요한 세팅은 확인 후 진행.

**Comment by hydro-carbo-nitro** [comment]
command line 상에서의 실행방법에 관한 간단한 매뉴얼 홈페이지에 입력.

**Comment by jhgoh** [comment]
설치 완료되었고 사용법도 [홈페이지](https://sichpc.khu.ac.kr/#SECTION_2_2)에 업데이트됨.
